# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WeatherToWakeUp' do

pod "SoundCloud-Cocoa-API"
pod "CZWeatherKit"

end

target 'WeatherToWakeUpTests' do

end

